name: Codex 자동 리뷰

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  review:
    if: github.event.pull_request.draft == false
    permissions:
      contents: read
      pull-requests: write
    uses: github/copilot-workflows/.github/workflows/pr-review.yml@v1
    secrets: inherit
    with:
      language: ko
